language: python
sudo: false
env:
  - PLONE_VERSION=4.3.x
  - PLONE_VERSION=5.0.x
  - PLONE_VERSION=5.1.x
python:
  - "2.7"
matrix:
  fast_finish: true
cache:
  pip: true
  directories:
  - eggs
  - downloads
install:
  - pip install -U pip setuptools zc.buildout
  - buildout -N -c test-$PLONE_VERSION.cfg buildout:download-cache=downloads code-analysis:return-status-codes=True annotate
  - buildout -N -c test-$PLONE_VERSION.cfg buildout:download-cache=downloads code-analysis:return-status-codes=True
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage --output-dir=htmlcov
  - pip install coveralls
  - coveralls
